### ISSUE TITLE
how to listen host Loopback

### ISSUE THREAD

**Issue by xxz199539** [rack/rack#2160] opened 2024-02-27 15:11 UTC
Hi, i want to listen ::1 and localhost in my rack server. my code:
```
def self.run_service(ser_proc_name, ser_cls_name, service_file, port)
	pid = fork do
		dir, file = File.dirname(service_file), File.basename(service_file)
		Dir.chdir(dir)
		load file
		$0 = ser_proc_name
            ssl_options = {
                :private_key_file => nil,
                :cert_chain_file => nil,
                :verify_peer => false,
            }
	    rack_handler_config = {
		:server => 'thin',
		:Host => '::1', 
		:Port => port
	    }
	    ser_cls_name = ser_cls_name.downcase.include?("web") ? ser_cls_name : ser_cls_name + "Service"
	    Rack::Handler::Thin.run(DDI.const_get(ser_cls_name), rack_handler_config) do |server|
                  server.ssl = true
                  server.ssl_options = ssl_options
	    end
	end
	Process.detach(pid)
end
```
but it not work for localhost, i got error when execute commad 'telnet localhost 20121'. so how can i config the 'Host' to listen 'localhost' and '::1' at the same time？
thanks.

**Comment by xxz199539** [comment] 2024-02-27 15:32
when i set 
```
rack_handler_config = {
		:server => 'thin',
		:Host => '::', 
		:Port => port
	    }
```
i can get response by 'telnet :: 20121' and 'telnet 0.0.0.0 2012'.so has the same way to support '::1' and 'localhost'?

**Comment by ioquatix** [comment] 2024-05-30 00:05
Thank you for bringing this up. After reviewing the situation, it's clear that this isn't a bug or issue with Rack itself. The behavior you're experiencing is related to how hosts are configured in your environment.

Your proposed solution to use :: as the host to listen on all interfaces, including localhost and ::1, is correct. This configuration should resolve the issue you were facing.

Closing this issue as it is not a bug with Rack. If you have any further questions or run into additional problems, feel free to reach out. GitHub Discussions are a better forum for these kinds of problems: https://github.com/rack/rackup

**Closed by ioquatix** 2024-05-30 00:05 UTC
