### ISSUE TITLE
Multipart filename can not be decoded.

### ISSUE THREAD

**Issue by comron** [rack/rack#323] opened 2012-01-21 00:44 UTC
I'm using a simple form on a rails application to upload a file, it looks as if the browser is not encoding the filename in the multipart "Content-Disposition" header, and as a result rack cannot decode the filename if it has a % in it, as it expects this to be the start of an escape sequence.

```
<form accept-charset="UTF-8" action="/documents.json" enctype="multipart/form-data" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input id="document_attachment" name="document[attachment]" type="file">
  <input type="submit">
</form>
```

Results in the following request

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Type:multipart/form-data; boundary=----WebKitFormBoundary2NHc7OhsgU68l3Al
Origin:http://localhost:3000
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.18 (KHTML, like Gecko) Chrome/18.0.1010.0 Safari/535.18

------WebKitFormBoundary2NHc7OhsgU68l3Al
Content-Disposition: form-data; name="utf8"

âœ“
------WebKitFormBoundary2NHc7OhsgU68l3Al
Content-Disposition: form-data; name="document[attachment]"; filename="100% of a photo.jpeg"
Content-Type: image/jpeg


------WebKitFormBoundary2NHc7OhsgU68l3Al--
```

As you can see the filename is not encoded, but the % causes rack to throw an error. Where exactly is the problem? It seems I have no control over the browser (Chrome and Firefox on OS X) encoding this name, and rack assumes it is always encoded, in multipart/parser.rb.

Thanks and sorry if this is the wrong forum for such a question.

**Comment by hlidotbe** [comment] 2015-02-11 16:18
This is still broken when there is a + in the filename and no percent.

`a+b.txt` gets unescaped to `a b.txt` because `Enumerable#all?` returns true when the set is empty (meaning no %.. present in the string).

**Comment by ab** [comment] 2015-11-25 23:20
Same comment as @hlidotbe: `"+"` is incorrectly decoded to `" "`.

Using `Utils.unescape` doesn't seem correct for percent decoding even if you think it's a good idea to percent decode filenames (despite no major browser percent encoding anything except `"`).

https://github.com/rack/rack/blob/d938cb58/lib/rack/multipart/parser.rb#L314
https://github.com/rack/rack/blob/d938cb58/lib/rack/utils.rb#L51

`Utils.unescape` uses `URI.decode_www_form_component`, which turns `+` into ` ` because it's expecting CGI style forms. Using `URI.unescape` instead would not have this problem.

**Comment by dentarg** [comment] 2015-12-06 22:02
Could this (and #755) be solved by using `Utils.unescape_path` as in https://github.com/rack/rack/commit/568cf7294d3c8abb84825514e91cf98c58a5e503?

**Comment by mhuggins** [comment] 2016-03-07 17:54
Hard to believe this is still an open issue from 4 years ago.  This is causing us upwards of hundreds of errors per day.

![invalid byte sequence in UTF-8](https://cloud.githubusercontent.com/assets/169093/13578059/f91ce09a-e452-11e5-923d-a999ddcec6c4.png)

Is there really no consensus on what the underlying issue is or what must be done to fix it?

**Comment by raggi** [comment] 2016-03-07 19:53
@mhuggins the problem is that all the browsers do different things. I started a test repo to gather the data, as there's no standard. It needs picking up and completing, then someone needs to align the multipart parser against it: https://github.com/rack/multifail

**Comment by raggi** [comment] 2016-03-07 19:54
@dentarg that would cause ArgumentError for the original given example

**Comment by raggi** [comment] 2016-03-07 19:58
FTR, https://tools.ietf.org/html/rfc7578 saying "MAY be percent encoded" is a fucking joke, because it means that the decoding of filenames is entirely ambiguous. That said, it is possible with the relatively clear definition in RFC7578 now to create a percent-encoding parser that will work for this task. There is nothing in MRI standard lib that conforms to this today.

**Comment by mhuggins** [comment] 2016-03-07 20:09
Thanks for the extra insight @raggi.

**Comment by chneukirchen** [comment] 2016-03-08 12:17
FTR, on POSIX systems filenames are anything not containing slashes or nul-bytes, so they should be treated as binary data in general.

**Comment by evinism** [comment] 2016-07-12 03:41
@raggi I might be completely wrong about this, but could "may be percent encoded" be referring to the case when the filename is a token, as opposed to quoted-string, as in [6266](https://tools.ietf.org/html/rfc6266#section-4.1)? In the case that it's a quoted string, the "correct" way is to escape it with `\"`, and that any non-control octets are allowed.

Under this interpretation, tokens should be fully percent-decoded, whereas quoted-strings should only be `\"` decoded, with `%22` slapped in there for compatibility's sake.

Personally it makes sense to me (and selfishly it would solve the issues I'm having right now) but I'm not sure it's a valid interpretation.

[token and quote definitions](https://tools.ietf.org/html/rfc2616#section-2.2)

**Comment by EddieOne** [comment] 2017-02-24 04:57
Another failing example

```
Unexpected error while processing request: invalid %-encoding ("EtnnicWars_(13).swf"
Content-Type: application/x-shockwave-flash

CWS,�\x���eX\۶-:��pw�������%!Aw'	������)
	/root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/uri/common.rb:383:in `decode_www_form_component'
```

**Comment by ioquatix** [comment] 2019-11-14 00:58
@raggi where did we get to with this issue? It could be great to revisit it.

**Comment by raggi** [comment] 2019-11-15 20:37
@ioquatix I got to the point where I'd made a large test suite that could be run through browser test or a similar service in order to validate the behavior of all browsers, but expired the timebox I'd allocated to the work.

Since then (as this is a very old issue) there was a new specification for multipart that I believe aimed to fix some of these issues and define correct behavior. I'm not sure if that RFC was published.

What I would recommend is:
 - lookup the new RFC, see if it was ratified. If it was, do a Gap analysis between our implementation and the RFC, looking at where we can better align.
 - use the multipart test suite against a modern set of browser clients (plus curl) to validate current behavior for common clients.
 - use inputs from the above to produce a smaller, concise test suite that documents our position on what we support in rack.
 - make tests green.
 - profit?

**Comment by raggi** [comment] 2019-11-15 20:38
Aforementioned test suite: https://github.com/rack/multifail

**Comment by ioquatix** [comment] 2020-02-04 22:58
This is the last outstanding issue holding up a v2.2.0 release.

I am happy to start reviewing the RFCs... but it would be great if someone has time to help and/or create a PR.

**Comment by jeremyevans** [comment] 2020-02-04 23:07
With the amount of work this requires, I don't think it should delay 2.2.0.  We can bump this to 3.0.0 if it is not ready in time for 2.2.0.

**Comment by ioquatix** [comment] 2020-02-04 23:30
From: https://tools.ietf.org/html/rfc7578#section-2

> 2.  Percent-Encoding Option
> 
>    Within this specification, "percent-encoding" (as defined in
>    [RFC3986]) is offered as a possible way of encoding characters in
>    file names that are otherwise disallowed, including non-ASCII
>    characters, spaces, control characters, and so forth.  The encoding
>    is created replacing each non-ASCII or disallowed character with a
>    sequence, where each byte of the UTF-8 encoding of the character is
>    represented by a percent-sign (%) followed by the (case-insensitive)
>    hexadecimal of that byte.

Also:

>    In most multipart types, the MIME header fields in each part are
>    restricted to US-ASCII; for compatibility with those systems, file
>    names normally visible to users MAY be encoded using the percent-
>    encoding method in Section 2, following how a "file:" URI
>    [URI-SCHEME] might be encoded.

So, I don't really think the RFC provides that much help here.

Taking a look at the current implementation:

https://github.com/rack/rack/blob/d075ee94a6d7775f4cceafeaa56489220fcf3a0c/lib/rack/multipart/parser.rb#L293-L325

It seems to be pretty robust, and there are now many specs for it, covering use cases described in this issue:

https://github.com/rack/rack/blob/d075ee94a6d7775f4cceafeaa56489220fcf3a0c/test/spec_multipart.rb#L228-L507

Including a spec for the filename from this issue:

https://github.com/rack/rack/blob/d075ee94a6d7775f4cceafeaa56489220fcf3a0c/test/spec_multipart.rb#L469

So, with that in mind, I think we can close this issue. I'm not saying we still have problems, just that if there are current issues, please start by opening a PR which adds a failing spec so we can consider how to address it best.

**Closed by ioquatix** 2020-02-04 23:30 UTC
Labels: Future, Refactor
