### ISSUE TITLE
Documentation for 2.0 version?

### ISSUE THREAD

**Issue by georgeu2000** [rack/rack#1106] opened 2016-08-25 16:19 UTC
Are there any breaking changes for v 2.0?

http://rack.github.io/ does not mention anything about 2.0. In fact, there has not been an update since February 7th, 2013.

https://github.com/rack/rack does not mention v 2.0 or any breaking changes.

**Comment by dubek** [comment] 2016-08-28 05:41
Duplicate of #1097 ?

**Comment by NobodysNightmare** [comment] 2016-10-31 12:39
@dubek It is... sad enough, that such an issue can have duplicates...

**Comment by mikegee** [comment] 2019-03-18 17:29
This issue is definitely a duplicate. Let's close this one. The discussion around 2.0 documentation should stay in one place.

**Closed** 2019-03-19 20:40 UTC
