### ISSUE TITLE
CWD forgotten after daemonizing

### ISSUE THREAD

**Issue by waiting-for-dev** [rack/rack#1813] opened 2022-02-20 05:44 UTC
That's how an app is daemonized:

https://github.com/rack/rack/blob/4e2c54187e6d2d989d50ce249199862ace42ecfc/lib/rack/server.rb#L438

The first argument to `Process.daemon` tells whether the current working directory must be changed to the root directory. From https://ruby-doc.org/core-3.1.1/Process.html#method-c-daemon:

> Unless the argument nochdir is true (i.e. non-false), it changes the current working directory to the root (“/”).

That means that when a rack server is launched with the `:daemonize` option, the directory where it has been launched is forgotten before reaching the handler. If the handler needs to use it to load a specific configuration file, it won't be possible.

You can reproduce the problem within a Rails application:

- Change the port specified on `config/puma.rb` to 2000.
- Run `bin/rails server -d`
- The server will listen on `3000` (Rails default) instead of `2000` (puma configuration).

I wonder which is the best way to fix it. Recently, a similar issue was addressed to allow keep STDOUT/STDERR open when daemonizing. See https://github.com/rack/rack/commit/d08cdbe7f940af0d2040fe65965caf1c8c531307. The way it was fixed was adding a new `--daemonize-noclose` option. Would you consider a new `--daemonize-nochdir` option? Or would you prefer adding the CWD to the options so that it can be handled downstream? I happily will work on a PR.

**Comment by ioquatix** [comment] 2022-02-21 08:10
Are you actually using rackup for creating a daemon? Why not use a process manager like launchd or systemd? Just trying to understand your use case, because I'm personally hoping we can either remove `rackup` (e.g. to a dedicated gem) or at least simplify it greatly. The current demonisation support is very limited as you are finding out.

**Comment by nateberkopec** [comment] 2022-02-21 15:22
Re: your reproduction, what puma version are you using? We removed daemonization in 5.0.

**Comment by jeremyevans** [comment] 2022-02-21 17:05
I am against removing rackup from the rack gem, and don't have a problem supporting additional daemonization features.  @waiting-for-dev Can you send a pull request?

**Comment by waiting-for-dev** [comment] 2022-02-22 04:01
Thanks for your feedback.

> Re: your reproduction, what puma version are you using? We removed daemonization in 5.0.

@nateberkopec, I used puma `5.6`. However, please notice that the issue is not related to puma. The daemonization happens on rack.

> I am against removing rackup from the rack gem, and don't have a problem supporting additional daemonization features. @waiting-for-dev Can you send a pull request?

Sure @jeremyevans. If you agree, I'll go with the `--daemonize-nochdir` option.

**Comment by ioquatix** [comment] 2022-02-22 05:44
Daemonization is best handled by an actual system designed for process management, that handles all the nuances that modern deployments required (e.g. handling crashes, restarts, configuration changes, etc). I believe Puma made the right choice here. IMHO, fully featured process management is out of scope for Rack, and as such I don't think we should encourage people to use Rack daemonization as it's a poor substitute for a real process manager.

**Comment by waiting-for-dev** [comment] 2022-02-22 05:54
> Daemonization is best handled by an actual system designed for process management, that handles all the nuances that modern deployments required (e.g. handling crashes, restarts, configuration changes, etc). I believe Puma made the right choice here. IMHO, fully featured process management is out of scope for Rack, and as such I don't think we should encourage people to use Rack daemonization as it's a poor substitute for a real process manager.

Hey @ioquatix, I completely agree with you when it comes to a production setup. However, having simple daemonization supported by Rack is useful for development purposes. WDYT? As I said, our use case is shipping a `hanami server` command only meant to be used in development. We'll encourage to use `puma` command (or any other handler command) in production.

**Comment by ioquatix** [comment] 2022-02-22 07:22
Can you explain the use case for daemonization for development use cases? You loose:

- Logging.
- Ability to restart easily.
- Debugging by attached IRB session.

I'm not sure what are the advantages.

**Comment by ioquatix** [comment] 2022-02-22 07:27
By the way, I'm not sure why we'd ever want to chroot with daemonization anyway, because the main reason for doing that was for daemons which:

1. Read config from disk.
2. `chdir("/")`
3. Disconnect from controlling terminals.

The point of the chdir IIRC is to avoid the situation where the daemon is attached to whatever directory it was started in (i.e. can't delete the directory). If you just started a daemon in some random directory (like your home directory), the daemon should definitely `chdir("/")`.

In the case of the rack application, we should be chdir to the same directory as `config.ru` by default IMHO (or maybe just not doing anything). That's because Rack is typically tied to assets on then file system and we don't want Rack to start trying to serve files under `/` by accident.

**Comment by jeremyevans** [comment] 2022-02-22 15:59
> Daemonization is best handled by an actual system designed for process management, that handles all the nuances that modern deployments required (e.g. handling crashes, restarts, configuration changes, etc). I believe Puma made the right choice here. IMHO, fully featured process management is out of scope for Rack, and as such I don't think we should encourage people to use Rack daemonization as it's a poor substitute for a real process manager.

Considering Rack already supports daemonization, it works, and people are using it, I don't see any reason to get rid of it.  Not everyone wants to deal with running a process manager, and not all Rack users are on Linux/Mac OS. 

> By the way, I'm not sure why we'd ever want to chroot with daemonization anyway, because the main reason for doing that was for daemons which:
> 
> 1. Read config from disk.
> 2. `chdir("/")`
> 3. Disconnect from controlling terminals.
> 
> The point of the chdir IIRC is to avoid the situation where the daemon is attached to whatever directory it was started in (i.e. can't delete the directory). If you just started a daemon in some random directory (like your home directory), the daemon should definitely `chdir("/")`.

The point of chdir after chroot is that you are changing to the directory that you chrooted to.  If you chroot to the current directory, after the chdir, you end up in the same directory.  The reason for this is if you don't chroot to `/`, there can be ways to escape the chroot.

> In the case of the rack application, we should be chdir to the same directory as `config.ru` by default IMHO (or maybe just not doing anything). That's because Rack is typically tied to assets on the file system and we don't want Rack to start trying to serve files under `/` by accident (i.e. if someone was mapping `Dir.pwd` + `PATH_INFO` or something equally ridiculous. Even better `chroot`/`jails`.

I agree that if we aren't using chroot, then it doesn't make sense to chdir to `/`.

**Comment by ioquatix** [comment] 2022-02-22 22:59
> Considering Rack already supports daemonization, it works, and people are using it, I don't see any reason to get rid of it. Not everyone wants to deal with running a process manager, and not all Rack users are on Linux/Mac OS.

The  reasons to get rid of it are:

1. It's poorly implemented/inflexible (as shown by this issue).
2. There are complex design choices to be made with different trade offs which don't belong in "Rack as a web server interface".
3. It's probably not appropriate for most typical use cases of `rackup`.
4. It's better solved with dedicated commands/systems (e.g. `daemonize`)

> Some people like to daemonize the server and launch the editor in the same process. Not my case, but IMHO it's a valid preference.

I'm not sure I understand what you mean. Do you mean terminal session?

> Are you proposing not to chdir / by default (so staying in the config.ru directory?).

Yes that's probably a more logical default.

I'd probably be more happy to move `rackup` to a dedicated gem, and if that's the case, I'm less concerned about the implementation creep.

**Comment by jeremyevans** [comment] 2022-02-22 23:11
> > Considering Rack already supports daemonization, it works, and people are using it, I don't see any reason to get rid of it. Not everyone wants to deal with running a process manager, and not all Rack users are on Linux/Mac OS.
> 
> The reasons to get rid of it are:
> 
> 1. It's poorly implemented/inflexible (as shown by this issue).

This issue does not show it is poorly implemented or inflexible, merely that it doesn't already have the feature requested.

> 2. There are complex design choices to be made with different trade offs which don't belong in "Rack as a web server interface".

You could make that argument for almost everything in rack aside from Lint/SPEC.  

> 3. It's probably not appropriate for most typical use cases of `rackup`.

This I agree with it.  That's why it is an option and off by default.

> 4. It's better solved with dedicated commands/systems (e.g. `daemonize`)

I don't necessarily agree with that.  In many cases, users do not want to have to rely on external tools just to run daemonized, and I don't think they should be forced to.

> > Are you proposing not to chdir / by default (so staying in the config.ru directory?).
> 
> Yes that's probably a more logical default.
> 
> I'd probably be more happy to move `rackup` to a dedicated gem, and if that's the case, I'm less concerned about the implementation creep.

`rackup` is too entrenched to move to a separate gem.  The loss of backwards compatibility in doing so would be far too high a cost, with few benefits, IMO.  `rackup` was one of the first things added to rack (less than 10 days after the project was started), and has shipped in every released rack version.

**Comment by ioquatix** [comment] 2022-02-23 03:14
I'm not convinced that it isn't buggy, e.g.

```
Finished in 2.798038s, 12.5088 runs/s, 26.8045 assertions/s.

  1) Error:
Rack::Server#test_0029_check pid file presence and dead process:
Errno::ENOENT: No such file or directory - /tmp/pidfile20220223-3795-9ah259
    <internal:core> core/errno.rb:48:in `handle'
    <internal:core> core/io.rb:914:in `sysopen'
    <internal:core> core/file.rb:1221:in `initialize'
    <internal:core> core/io.rb:582:in `read'
    /home/runner/work/rack/rack/lib/rack/server.rb:453:in `check_pid!'
    test/spec_server.rb:411:in `test_0029_check pid file presence and dead process'

35 runs, 75 assertions, 0 failures, 1 errors, 0 skips
/home/runner/.rubies/truffleruby-head/bin/truffleruby -w test/spec_show_exceptions.rb
Run options: --seed 28668
```

maybe a race condition with pidfile handling.

**Comment by waiting-for-dev** [comment] 2022-02-23 14:07
After talks with the Hanami team, we've decided not to support daemonization for now (mainly because of the lack of stdout/stderror and how cumbersome it is to start/restart the server). We might change opinion in the future, though.

Anyway, current behavior also causes buggy behavior in Rails+puma, so I'll be more than happy to submit a PR fixing it if Rack's team agrees it's the direction you want to take. I'll wait for your final decision. Thanks, folks!

**Comment by jeremyevans** [comment] 2022-02-23 15:51
If you aren't going to be using it, I don't see a need for a PR to add features.  However, if you find bugs in the existing support, please do submit a PR to fix them.

**Comment by ioquatix** [comment] 2022-02-23 22:55
@jeremyevans do you agree daemonization should preserve cwd?

**Comment by jeremyevans** [comment] 2022-02-23 23:09
@ioquatix Agreed. Should be as simple as changing `nil` to `true` in the `daemon` call.

**Comment by ioquatix** [comment] 2022-02-23 23:19
@waiting-for-dev can you make a PR for that?

**Comment by jeremyevans** [comment] 2022-02-24 00:24
Since it is such as simple PR, I took care of it in #1820.

**Closed** 2022-02-24 00:37 UTC

**Comment by waiting-for-dev** [comment] 2022-02-24 04:24
Thanks!
