### ISSUE TITLE
Rack::Cascade option to avoid pass to a next app unless header X-Cascade='pass'

### ISSUE THREAD

**Issue by pettomartino** [rack/rack#1185] opened 2017-06-28 15:44 UTC
Hi guys,
I ran into a case which is desirable to respond 404 for `apps` on top of the stack.
So let's suppose:
```ruby
class Images
   def call(env)
     #...
     [404, {CONTENT_TYPE => "text/plain"}, ["Some special content"]]
   end
end

class Home
   def call(env)
     #...
     [404, {CONTENT_TYPE => "text/plain"}, ["Default content"]]
   end
end

Rack::Cascade.new [
    Images,
    Home
]
```

A way that I imagine to deal with that is to respect `X-Cascade` header using some optional attribute on constructor.
```
def initialize(apps, catch=[404, 405], require_x_cascade=false)
```
`require_x_cascade=true` makes `Rack::Cascade` stops on first `404` unless header contains `X-Cascade: pass`

does it make any sense? Would you guys accept a PR on that?

**Comment by jeremyevans** [comment] 2020-01-15 19:26
A PR for this seems reasonable, so please submit one if you would still like this behavior added.  We would probably want to use a keyword argument instead of a positional argument for this, I think.

Closing this now as it is not a bug in rack.

**Closed by jeremyevans** 2020-01-15 19:26 UTC
