### ISSUE TITLE
Use Rack::Static to mount a directory outside of the project directory

### ISSUE THREAD

**Issue by gueorgui** [rack/rack#1523] opened 2020-01-26 22:42 UTC
I'm building a Rails Engine that includes some assets built through Webpacker, and I'm following [the Webpacker documentation](https://github.com/rails/webpacker/blob/master/docs/engines.md#use-a-separate-middleware) on this.

I would like to distribute this engine as a gem, and to serve the engine's assets directly from the engine's gem, through a `Rack::Static` middleware in the host application.

This is what I'm trying:

```ruby
# in the engine project: lib/my_engine/engine.rb
module MyEngine
  class Engine < ::Rails::Engine
    (...)
    config.app_middleware.use(
      Rack::Static,
      urls: ['/myengine'], root: File.join(__dir__, 'public')
    )
  end
end
```

If I set the `root:` option for `Rack::Static` to a relative path (eg: `my_engine/public`) and then create a symlink in the host project to the relevant directory in the gem, this will work, however the code above, which generates an absolute path, does not work.

What could I do to fix this?

**Comment by ioquatix** [comment] 2020-01-27 01:35
It seems like it should work. How is the root directory computed in the `Rack::Static` implementation.

**Comment by gueorgui** [comment] 2020-01-27 16:19
It also seems like it should work to me. `Rack::Static`'s constructor initializes a file server by passing the root path it receives to `Rack::Files`, which in turn expands the path with `File.expand_path` to get a full absolute path.

Could it be the Rails web server (eg Puma) applying some restrictions so that content outside of the Rails app directory cannot be served?

**Comment by jeremyevans** [comment] 2020-01-30 15:16
It certainly appears more likely the problem is external to Rack, though I'm not sure where. Since it doesn't appear this is a bug in Rack::Static, I'm going to close this now. If you can discover the root cause of the issue and think it is a bug in Rack, please post more details and we can reopen.

**Closed by jeremyevans** 2020-01-30 15:16 UTC
