### ISSUE TITLE
Write RBS files

### ISSUE THREAD

**Issue by ParadoxV5** [rack/rack#1967] opened 2022-09-20 00:33 UTC
I am currently tinkering with Rack and RBS. Introduced with Ruby 3, [ruby/rbs](https://github.com/ruby/rbs/) is a type-checking language for Ruby.

Currently, [RBS for Rack is (somewhat) available in the Gem RBS collection](https://github.com/ruby/gem_rbs_collection/tree/HEAD/gems/rack). @mame (I’m not sure if they help out here too or not) auto-generated and edited that RBS document and pulled via ruby/gem_rbs_collection#36. However, it has possible mistakes and undocumented fields. Examples from [`Rack::Response`](https://rubydoc.info/gems/rack/2.2.2/Rack/Response) alone:

* The attribute `Rack::Response#body` should probably follow [the `SPEC` § The Body](../blob/HEAD/SPEC.rdoc#the-body-), but the RBS restricts it to one or an Array of `Rack::Lint` or `nil`.
* I’ve been working around the above with `Rack::Response.[]`, whose args are untyped in the RBS.
* `Rack::Response#each` is also missing RBS for `&block`.

I have considered reviewing that RBS document myself, but I hesitated because I’m affiliated with neither Rack nor RBS. I decided to file an issue here instead of there because ideally, the RBS of a Gem should be managed, updated and shipped by the Gem library itself. (BTW, that RBS entry implies targeting Rack 2.2.2, whereas Rack just got a new major version recently.)

> Note that if you are the maintainer of the gem, you should consider moving RBS files to the gem's code repository and including them in the gem package instead.

⸺ [`ruby/gem_rbs_collection`, `docs/CONTRIBUTING.md`, § Become a code owner](https://github.com/ruby/gem_rbs_collection/blob/52f2afbc5e8a5638082cacfa6325ee6f0d9f22af/docs/CONTRIBUTING.md#become-a-code-owner)

**[TL;DR]** In conclusion, I propose compiling and maintaining Rack’s RBS ourselves. We can potentially start by porting the Collection RBS (linked above) or regenerating a stub.

**Comment by ParadoxV5** [comment] 2022-09-20 00:34
P.S. Looks like our ~~favourite~~ child Rails also has RBS at [pocke/rbs_rails](https://github.com/pocke/rbs_rails). I can tell from pocke/rbs_rails#174 that they would welcome our engagement.

**Comment by jeremyevans** [comment] 2022-09-20 00:57
Personally, I'm not interested in maintaining RBS for rack.  Things like the response body (either enumerable or callable), the stream passed to a callable body,  the logger, the session, and the input/error streams are not required to be a specific class, by design.

RBS is designed to make you think in forms of concrete types, but Rack is designed for duck typing, so there is always going to be an impedance mismatch, until RBS supports a duck-typing based approach (e.g. the object can be any type, but must respond to these methods).  With the `env`-based approach, the values for certain keys are expected to be certain types, but AFAIK that cannot be properly handled by RBS (RBS is designed for hashes that have uniform key/value types). There are probably other issues with supporting RBS for rack that I'm neglecting as well.  To be fair, these are not RBS-specific issues, the general duck-typing approach rack uses is unlikely to work well with anything designed for static typing.

I don't think we should ship RBS with rack.  However, if another rack committer wants to ship RBS with rack and can commit to keeping it up to date with changes in rack, I don't object to shipping RBS with rack.

**Comment by ParadoxV5** [comment] 2022-09-20 01:43
> RBS is designed to make you think in forms of concrete types, but Rack is designed for duck typing, so there is always going to be an impedance mismatch, until RBS supports a duck-typing based approach (e.g. the object can be any type, but must respond to these methods).

I am with you that RBS doesn’t excel at duck types despite duck typing being the Ruby norm. RBS (currently) implements duck typing with Interfaces, which wraps a list of available methods into something that isn’t a Ruby Module or Class. Bridging all of Rack’s duck types in RBS is both valuable and cumbersome.

> With the env-based approach, the values for certain keys are expected to be certain types, but AFAIK that cannot be properly handled by RBS (RBS is designed for hashes that have uniform key/value types).

AFAIK, neither had any static typing programming language able to specify value types for each key independently. We Rubyists are grateful that we get quacks from anything that quacks.

> However, if another rack committer wants to ship RBS with rack and can commit to keeping it up to date with changes in rack, I don't object to shipping RBS with rack.

Yeah, if the Collection’s RBS is complete and up-to-date, I wouldn’t bring RBS up here (or there). **How about we open an RBS -specific branch?**  Somewhere interested contributors can submit PR instead of `main` until the day comes.

**Comment by rafaelfranca** [comment] 2022-09-20 01:51
Reviewing and merging PRs to any branches is still maintaining.

I'm all for types. Heck, my team is pushing Sorbet adoption in the community and creating tooling like the ruby-lsp, tapioca and helping Stripe to maintain Sorbet. But, I don't want to maintain RBS interfaces for a thing that type systems can't properly type.

I'd say that most Rack users would not benefit from Rack being properly typed. Maybe some methods in `Rack::Utils` but the Rack Spec itself isn't something they often interact with. Typing many big Rails applications, I so far didn't encounter any use case that would really benefit from rack being properly typed.

The better we can do is provide `Rack::Lint`, which checks your rack program/middleware at runtime.

**Comment by jeremyevans** [comment] 2022-09-20 01:51
> Yeah, if the Collection’s RBS is complete and up-to-date, I wouldn’t bring RBS up here (or there). **How about we open an RBS-specific branch?** Somewhere interested contributors can submit PR instead of `main` until the day comes.

I am against that approach.  If we aren't going ship RBS, we shouldn't maintain a branch with RBS.  Until we decide to ship RBS, it seems like `gem_rbs_collection` would be a better place to maintain RBS for rack.

**Comment by ParadoxV5** [comment] 2022-09-20 02:41
I do see typing is secondary for Rack and am not against the decision to not ship RBS.

Although, I’m also curious why the YARDocs have (duck) types. FYI, there are tools such as [AaronC81/sord](https://github.com/AaronC81/sord) that can export YARDocs’ types to RBS. I haven't played with any myself and don’t know if they suffice.

**Comment by rafaelfranca** [comment] 2022-09-20 02:46
For duck types I remember sord just generated `Handles duck types (T.untyped/untyped)`. That is pretty much what tapioca generates for all of rack automatically without rack maintainers having to do anything.

**Comment by mame** [comment] 2022-09-20 07:30
In general, I don't think it is a good idea for a third party to ask the project maintainers to maintain RBS. I'm afraid that it will only cause unnecessary friction. It is welcome if the project maintainers themselves want to manage RBS voluntarily. However, in this case, it is obvious that the maintainers are not willing to do so. I think it is better to close this issue for now.

I'm sorry about the low quality of rack rbs in gem_rbs_collection. I'd like @ParadoxV5 to send a PR to ruby/gem_rbs_collection side.

**Comment by ioquatix** [comment] 2022-09-20 08:52
I'm okay with supporting RBS in Rack, but I want to see the clear advantage, e.g. better validation of servers, better validation of apps, better maintainability, etc.

I'm also not sure why we should choose RBS over Sorbet or vice versa. I'd rather we can do something that supports both if possible.

**Comment by ParadoxV5** [comment] 2022-09-20 16:46
Hints on typing are beneficial for knowing what can be used and what not. (E.g., [Rack 3 introduced additional constraints.](../blob/HEAD/UPGRADE-GUIDE.md)) However, indeed advantages currently are not significant enough between RBS, Sorbet, and just clearer YARDocs and perhaps a highlight on `Rack::Lint`.

---

I’ll bring this discussion over to `ruby/gem_rbs_collection` in a movement. When that RBS is complete and up-to-date, we can discuss if it’s worth porting it here (I can help a bit with maintaining it).

**Closed** 2023-03-07 21:53 UTC

**Comment by ioquatix** [comment] 2023-03-07 22:01
@tenderlove do you mind explaining what was done?

**Comment by tenderlove** [comment] 2023-03-07 23:34
Sure, I don't want to maintain RBS files, and it looks like @ParadoxV5 has submitted them to `gem_rbs_collection`.

**Comment by ParadoxV5** [comment] 2023-03-07 23:47
yeah, essentially forwarded this to ruby/gem_rbs_collection#210

**Comment by ioquatix** [comment] 2023-03-08 03:39
Ok - I hope there is a future where RBS attached to a gem is largely automatic part of distribution/gem building and not any kind of maintenance overhead.
