### ISSUE TITLE
Failed to handle content-type boundary which is double-quoted

### ISSUE THREAD

**Issue by JimmyMa** [rack/rack#858] opened 2015-05-20 09:07 UTC
When the http request is below, that the boundary is double quoted:

..+...!HPUT /v2/apps/5c3f4c72-cc42-431f-964d-24ce54258608/bits?async=true HTTP/1.1
Host: xxxxxx.xxxxx.xxx
User-Agent: go-cli 6.7.0-c38c991 / windows
Content-Length: 2930
Accept: application/json
Content-Type: multipart/form-data; boundary="1e094f28e9b118c2c6956e4272ffd722c770950f7c66d201cf0642a5371e"
Via: 1.1 AQAAAA6K3wA-

Then got below error :
error -- bad content body -- ["/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:78:in `block in fast_forward_to_first_boundary'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:72:in `loop'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:72:in `fast_forward_to_first_boundary'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb:15:in `parse'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/multipart.rb:25:in `parse_multipart'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/request.rb:384:in `parse_multipart'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/request.rb:208:in `POST'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/request.rb:231:in `params'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:893:in `call!'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'", "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'"]

should this line https://github.com/rack/rack/blob/master/lib/rack/multipart.rb#L12 be:
     MULTIPART = %r|\Amultipart/.*boundary=?([^;,]+)?|ni

**Comment by jodosha** [comment] 2015-05-21 07:25
According to [RFC 2046](https://www.ietf.org/rfc/rfc2046.txt) (Section 5.1.1 - Common Syntax), quoting a multipart boundary is allowed:

> WARNING TO IMPLEMENTORS:  The grammar for parameters on the Content-
   type field is such that it is often necessary to enclose the boundary
   parameter values in quotes on the Content-type line.  This is not
   always necessary, but never hurts. Implementors should be sure to
   study the grammar carefully in order to avoid producing invalid
   Content-type fields.  Thus, a typical "multipart" Content-Type header
   field might look like this:

     Content-Type: multipart/mixed; boundary=gc0p4Jq0M2Yt08j34c0p

>   But the following is not valid:

     Content-Type: multipart/mixed; boundary=gc0pJq0M:08jU534c0p

 >  (because of the colon) and must instead be represented as

     Content-Type: multipart/mixed; boundary="gc0pJq0M:08jU534c0p"

**Comment by jodosha** [comment] 2015-05-21 08:20
@JimmyMa Can you please have a look at #861 ? The test case introduced by that PR, reproduces your problem and **it supposed to fail, but it doesn't**. Am I missing something?

According to your stack trace, you're using 1.5.2. The test passes with that version, with 1.5.3 and master.

**Comment by JimmyMa** [comment] 2015-05-21 14:29
@jodosha Thanks a lot for your quick reply.

Here is the http request that failed, is this covered in your test? Thanks a lot.
-----------------------
PUT /v2/apps/xxxxxxxxxxxxxxx/bits?async=true HTTP/1.1
Host: xxx.xx.xx.xx.xx
User-Agent: go-cli 6.7.0-c38c991 / windows
Content-Length: 2930
Accept: application/json
Content-Type: multipart/form-data; boundary="1e094f28e9b118c2c6956e4272ffd722c770950f7c66d201cf0642a5371e"
Accept-Encoding: gzip

--1e094f28e9b118c2c6956e4272ffd722c770950f7c66d201cf0642a5371e
Content-Disposition: form-data; name="resources"

[]
--1e094f28e9b118c2c6956e4272ffd722c770950f7c66d201cf0642a5371e
Content-Disposition: form-data; name="application"; filename="application.zip"
Content-Type: application/zip
Content-Length: 2508
Content-Transfer-Encoding: binary

PK........U..F................Procfileweb: node app.js 
PK....].........PK........U..F................READMEBe sure you enter 'node app.js' when you push the application and cf asks you for a Custom startup command
(I cant remember how this can be done automatically)
PK..$&..........PK........U..F................app.jsrequire("cf-autoconfig");
var express = require("express");

**Comment by jodosha** [comment] 2015-05-25 15:26
@JimmyMa I've tried it locally, the payload above is invalid. It's missing the closing line:

```
--1e094f28e9b118c2c6956e4272ffd722c770950f7c66d201cf0642a5371e--
```

By adding that line, it works as expected. Please let me know if it isn't the case for you and reopen this ticket.

/cc @spastorino @tenderlove can you please close this ticket? Thank you!

**Closed** 2015-05-25 16:43 UTC

**Comment by tenderlove** [comment] 2015-05-25 16:45
@jodosha thanks!
