### ISSUE TITLE
incompatible with nginx client_body_in_file_only on; (bad conent body EOFError)

### ISSUE THREAD

**Issue by MichaelSp** [rack/rack#906] opened 2015-06-29 10:53 UTC
To overcome puma/unicorn/... timeout errors on big file uploads I'd like nginx to handle the upload completely upfront. And after the body is stored on disk, contact the rack-application.
But rack doesn't seem to deal with an empty body (actually the content is 'off').
The body is stored on disk and the file name is set as HTTP header depending on the configuration of nginx. For me it's the `HTTP-X-FILE`-header:

```
location /upload {
        limit_except POST {
            proxy_pass             http://rails;
        }

        client_body_temp_path      /tmp/uploads/;
        client_body_in_file_only   on;
        client_body_buffer_size    1024K;
        client_max_body_size       500G;

        proxy_pass_request_headers on;
        proxy_set_header           X-FILE $request_body_file;
        proxy_set_body             off;
        proxy_redirect             off;
        proxy_pass                 http://rails/;

        track_uploads uploads 30s;
}
```

While I don't think this is a bug in rack or rack necessarily has to deal with `client_body_in_file_only on;`, there should be a way to get the idea working. So what is the recommended way?

By the way: I'm aware of `http://wiki.nginx.org/HttpUploadModule` but as this is not part of stock ubuntu package I cannot use it.

Full stack trace:

```
Puma caught this error: bad content body (EOFError)
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:97:in `block in fast_forward_to_first_boundary'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:95:in `loop'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:95:in `fast_forward_to_first_boundary'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/multipart/parser.rb:53:in `parse'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/multipart.rb:25:in `parse_multipart'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/request.rb:375:in `parse_multipart'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/request.rb:207:in `POST'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:39:in `method_override_param'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:27:in `method_override'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:15:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/static.rb:113:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiler.rb:276:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:518:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
/home/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by bruno** [comment] 2015-07-01 03:15
The error seems very similar to the one reported on #903 ... I am tracking down a different error however whilst looking through the open issues, I noticed that, just thought I'd mention it.

**Comment by jvbreen1** [comment] 2016-02-24 18:27
@MichaelSp Have you been able to work around this successfully?

**Comment by MichaelSp** [comment] 2016-02-26 09:49
Yes. Kind of. Here is my current configuration that works quite nicely

    location /upload/progress {
        report_uploads uploads;
    }
    location ~ (/upload/releases) {
        limit_except POST {
            proxy_pass             http://rails;
        }

        client_body_buffer_size    1024K;
        client_max_body_size       500G;

        proxy_set_header    X-Request-Start "${msec}";
        proxy_set_header    X-Forwarded-Host $host;
        proxy_set_header    X-Forwarded-Server $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_set_header    Host $host:$server_port;
        proxy_redirect      off;
        proxy_pass          http://rails;

        track_uploads uploads 30s;
    }

There is just one drawback, that should be addressed by rack, I think: The files gets uploaded to a /tmp file then the rails/rack request starts where the file is copied from /tmp to another /tmp file. 

So support for `client_body_in_file_only on;` is still appreciated.

**Comment by jeremyevans** [comment] 2020-01-17 20:28
Since the need for this seems fairly limited, and there is already an existing (if suboptimal) workaround, I'm going to close this (it's not a bug in rack).

I think it should be possible to support this using an external rack middleware.  If you think changes to rack itself are needed, that could not be accomplished via a middleware, please submit a pull request.

**Closed by jeremyevans** 2020-01-17 20:28 UTC
