### ISSUE TITLE
 Error during failsafe response: Invalid request parameters: invalid %-encoding

### ISSUE THREAD

**Issue by Marcellllll** [rack/rack#1390] opened 2019-09-21 22:51 UTC
Hi,

We are having an issue with (hack) bots sending requests with raw data params which cause 500 errors.

The requests are like this:
`localhost:5000/kdatebase/index_.asp?q=(Execute("Execute(""On+Error+Resume+Next:Response.Clear:Function+bd%28byVal+s%29%3AFor+i%3D1+To+Len%28s%29+Step+2%3Ac%3DMid%28s%2Ci%2C2%29%3AIf+IsNumeric%28Mid%28s%2Ci%2C1%29%29+Then%3AExecute%28%22%22%22%22bd%3Dbd%26chr%%28%26H%22%22%22%22%26c%26%22%22%22%22%29%22%22%22%22%29%3AElse%3AExecute%28%22%22%22%22bd%3Dbd%26chr%%28%26H%22%22%22%22%26c%26Mid%28s%2Ci%2B2%2C2%29%26%22%22%22%22%29%22%22%22%22%29%3Ai%3Di%2B2%3AEnd+If%22%22%26chr%%2810%29%26%22%22Next%3AEnd+Function:Response.Write(""""->|""""):Execute(""""On+Error+Resume+Next:""""%26bd(""""44696D20533A533D5365727665722E4D61707061746828222E2229266368722839293A53455420433D4372656174654F626A6563742822536372697074696E672E46696C6553797374656D4F626A65637422293A496620457272205468656E3A4572722E436C6561723A456C73653A466F722045616368204420696E20432E4472697665733A533D5326442E44726976654C657474657226636872283538293A4E6578743A456E642049663A526573706F6E73652E5772697465285329"""")):Response.Write(""""|<-""""):Response.End"")")

I managed to reproduce this with Postman by making a POST request just pasting the above string (without the q) as raw data and managed to reproduce the error we are getting in our production system:
   _Invalid or incomplete POST params 
  Error during failsafe response: Invalid request parameters: invalid %-encoding ((Execute("Execute(""On+Error+Resume+Next:Response.Clear:Function+bd%28byVal+s%29%3AFor+i%3D1+To+Len%28s%29+Step+2%3Ac%3DMid%28s%2Ci%2C2%29%3AIf+IsNumeric%28Mid%28s%2Ci%2C1%29%29+Then%3AExecute%28%22%22%22%22bd%3Dbd%26chr%%28%26H%22%22%22%22%26c%26%22%22%22%22%29%22%22%22%22%29%3AElse%3AExecute%28%22%22%22%22bd%3Dbd%26chr%%28%26H%22%22%22%22%26c%26Mid%28s%2Ci%2B2%2C2%29%26%22%22%22%22%29%22%22%22%22%29%3Ai%3Di%2B2%3AEnd+If%22%22%26chr%%2810%29%26%22%22Next%3AEnd+Function:Response.Write(""""->|""""):Execute(""""On+Error+Resume+Next:""""%26bd(""""44696D20533A533D5365727665722E4D61707061746828222E2229266368722839293A53455420433D4372656174654F626A6563742822536372697074696E672E46696C6553797374656D4F626A65637422293A496620457272205468656E3A4572722E436C6561723A456C73653A466F722045616368204420696E20432E4472697665733A533D5326442E44726976654C657474657226636872283538293A4E6578743A456E642049663A526573706F6E73652E5772697465285329"""")):Response.Write(""""|<-""""):Response.End"")"))
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/query_parser.rb:72:in `rescue in parse_nested_query'
  

We have a filter set up to handle bad parameters, like this :

```
class HandleBadEncodingMiddleware

  def initialize(app)
    @app = app
  end

 
  def call(env)
    bad_form_data = false

    begin
      Rack::Utils.parse_nested_query(env['QUERY_STRING'].to_s)
    rescue Rack::Utils::InvalidParameterError, Rack::Utils::ParameterTypeError, Rack::QueryParser::InvalidParameterError, Rack::QueryParser::ParameterTypeError => e
      env['QUERY_STRING'] = ''
      bad_form_data = true
    end

    if bad_form_data
      [400, headers, ['Bad Request']]
    else
      @app.call(env)
    end
  end
end
```

The problem is that the Rack::Utils.parse_nested_query passes successfully, and the error only happens in the actual call.

Is there any way we can cleanly handle these types of requests without causing 500 errors ?

Kind regards,
Marcel

(sorry for the bad text formatting)

**Comment by jeremyevans** [comment] 2020-01-11 21:23
Can you provide a full backtrace or self-contained reproducible example for this issue?  `Rack::Utils.parse_nested_query` can't directly return a 400 response, so all it can do is raise an exception.  There would need to be something at a higher level to rescue the exception and return a 400 response.

Your middleware looks basically OK, but you are only parsing the QUERY_STRING.  Since the issue is POST requests, it is possible the code in question is the result of query parsing the body.  But that is just a guess, a full backtrace or self-contained reproducible example is necessary for proper analysis.

**Comment by jeremyevans** [comment] 2020-01-22 20:33
Closing as this doesn't appear to be a bug in rack, it appears to be expected behavior.  We could potentially add a middleware that parses query parameters (and body if applicable) and returns a client error result for invalid parameters, but that's a new feature.  Please submit a pull request if you think that would be helpful.

**Closed by jeremyevans** 2020-01-22 20:33 UTC
