### ISSUE TITLE
String reuse in body each() - Is Rack::Response Array-based buffering intentional?

### ISSUE THREAD

**Issue by julik** [rack/rack#1722] opened 2020-11-29 23:07 UTC
In our library - https://github.com/WeTransfer/zip_tricks - we allow output from an iterable object. Every yielded String contains a chunk of the ZIP file being output. At a certain point we found that we can accelerate output if we perform some buffering in the library. We were able to also reduce allocations _greatly_ by reusing the same String object to contain our output buffer. We then `yield` that same String over and over, just allow it to have different contents. Not the greatest fan of mutable strings in Ruby but if we have them why not use them?

Now, this works great with web servers, since they pick up the String that is given to them, and then do whatever is necessary to either chop it up (which performs a copy-on-write realloc) or do something like `IO#syswrite` into the socket.

However, this optimisation implies that the String yielded from the Rack body is not going to be retained - or, if the caller of `each` wishes to retain that string, it will copy the string. I could not find  any reference to identity semantics for Rack response bodies. The SPEC only says that

> The Body must respond to each and must only yield String values.

but it does not say whether it is acceptable to yield the same String object again and again, just with it having different contents. To my mind this feels like a great optimisation trick and it should be acceptable to expect the caller of `#each` to copy the String on its own - should it so desire, but I wonder what other opinions are there.

For the most part this setup works fine - as long as the output of the Rack body is not eagerly stored somewhere. However, I have encountered retains in a somewhat unexpected place - in `rack-test`. There, a `MockResponse` is used, which - in turn - uses a `Rack::Response`. And inside the `Rack::Response` there is - predictably - an Array of strings yielded by the actual body, which then contains multiple instances of exactly the same string. This subtly breaks testing, and would probably also break `Rack::Response` for anyone yielding the same object from `#each`.

And so I wonder. Wouldn't it be better, in general, for the purpose of _encouraging design of streaming-enabled applications_ with Rack, to codify the fact that the strings yielded from the Rack body **may** be the same string by identity, and _if_ the consumer of `#each` wishes to stash the output somewhere it must do so including a `.dup` call on the Strings it receives? It is an obscure optimisation for sure, but if you have a large streaming output the amount of savings you can have in allocations can be _massive_ (best case you can stream with constant memory use).

/cc @felixbuenemann

**Comment by ioquatix** [comment] 2020-11-29 23:49
I've thought about this quite a bit with Falcon and how it implements buffering. The key issue is as you say, if you store a reference to the string (in a queue) and it's not flushed, then that string gets mutated, do you basically trash the output data stream?

I think the general answer is, yes, once you yield a string, you've transferred ownership.

In `protocol-http`, we explicitly `dup` strings: https://github.com/socketry/protocol-http/blob/6af4239f683061787af3071c5814134b3931218d/lib/protocol/http/body/buffered.rb#L81-L87 to avoid problems.

My understanding is, Ruby implements copy on write, so in theory, you should be able to reuse the same source buffer, provided you call `dup` on the part you yield.

So maybe something like this? (just a stab in the dark)

```
buffer = String.new

while data_remaining?
  fill_buffer(buffer) # allocates string buffer
  yield(buffer.dup) # does this actually copy the string here?
  buffer.clear # clears the string buffer, if the dup is still retained, this should trigger CoW.
end
```

What we should probably do is investigate the behaviour of current servers and then settle on something w.r.t. ownership. But I assume it's not going to be favourable to your position, even if I agree it would be better.

As you say, maybe what we could do is introduce explicit guarantees into a streaming interface.

**Comment by ioquatix** [comment] 2020-11-29 23:51
By the way, there are two positions:

1. After yielding a string, you must not modify it, or
2. After yielding a string, you may reuse it.

It basically comes down to those two choices. A server *could* implement `dup` if it wants to hold on to the buffer, or if the server was doing direct I/O, it wouldn't matter anyway.

**Comment by julik** [comment] 2020-11-30 00:14
Correct. I am actually in favor of option 2. because it is possible to know where you want to copy, but if you are forced to copy you will be paying the performance cost always. In this case, for example, in Async you would `.dup` when pushing the string into your body queue since in this instance the caller cares about holding a copy of the String.

Direct writes and extra allocations are tricky indeed, especially in a language without a good `Slice` type. If you are interested there was some research into allocs we did in https://github.com/WeTransfer/zip_tricks/pull/84#issuecomment-725810808 - basically, yes - `#dup` will only use more space to store the object reference, but as soon as the original is touched you will incur a copy.

**Comment by felixbuenemann** [comment] 2020-11-30 00:54
At the core the biggest problem is that Ruby only uses CoW when duping full strings, as soon as you slice a string it is immediately copied.

This differs from eg. Go, where slices of strings are just a reference to a region in the source slice which makes buffering a lot easier.

However even if you can dup a full string that is then immediately reused you gain nothing from CoW since as soon as you reuse it the duped string is copied.

A big problem with memory intensive tasks is that the Ruby (MRI) is not aggressive enough to clean up those big allocations before the next one happens and freed regions also fragment with smaller allocations leading to continuous heap growth.

While you can use smaller chunks to reduce memory bloat, the only way to avoid it is to reuse buffers or pass through all data unmodified – which can be bad for performance.

**Comment by ioquatix** [comment] 2020-11-30 08:46
Okay, so do we try to solve this at the VM level, or give up on that and try to fix it at the Rack level?

**Comment by julik** [comment] 2020-11-30 13:08
My preference would be to codify in SPEC that the string may be reused and if the caller wishes to retain it it has to copy it. Something like:

> The string yielded from `each` of the body may be reused, modified and cleared later - the body holds ownership over that string. If the string is not consumed immediately (writing it into a socket, file descriptor etc.) before returning control to the `each` method of the body, the code calling `each` is responsible for duplicating the string.

We would then need to examine the Rack code for instances where the yielded string is retained and introduce `dup` there (like in the Response object).

I don't think the VM is going to solve this, at least not in a close timeframe

**Comment by jeremyevans** [comment] 2020-11-30 16:00
The problem with requiring body copies in SPEC is that in the case where string-reuse is not done, you've doubled the memory use for the body for no benefit, and very few users are likely to be reusing strings.  I prefer leaving this unspecified.  Users who want to use string-reuse probably aren't going to want to give up the optimization transparently by a middleware that dups all of the strings.

In terms of `rack-test`, I don't have a problem making it dup bodies.  It's only used for testing, so performance is not as great a concern, and generally in testing you are using small bodies anyway.

**Comment by julik** [comment] 2020-11-30 16:51
> The problem with requiring body copies in SPEC is that in the case where string-reuse is not done, you've doubled the memory use for the body for no benefit

I am suggesting not to require body copies but to signal that they _may_ be required for buffering wrappers/servers. This way the problem moves to the caller (one side of the equation) as opposed to being equally problematic for both the developer of the callee (the body) and the developer of the caller (server/middleware)

> In terms of rack-test, I don't have a problem making it dup bodies

I actually wanted to try that, but it turns out that `rack-test` calls `each` on the body of a `Rack::Request`, which cannot be overridden - and it buffers using an Array, thus breaking when a string is reused.

**Comment by ioquatix** [comment] 2020-11-30 22:47
There should be no cost to calling dup on a string if that string itself is not modified, so I have no problem changing `Rack::Response` to call dup internally, but I'd be very careful about measuring this assumption and preventing regressions i.e. we should be measuring allocation counts and putting that in a test if we are going to rely on `String#dup` to be fast.

**Comment by jeremyevans** [comment] 2020-11-30 23:15
While the cost isn't major as the underlying string content is not duplicated, there is still a cost as the duped object still takes a separate object slot and results in additional work for the garbage collector.

I don't think we should change `Rack::Response` for this.  `Rack::Response` is not what is doing the buffering, at least in the current implementation.  Maybe @julik is using an old version of Rack, before 2.1.0 / 8c62821f4a464858a6b6ca3c3966ec308d2bb53e?  Or using a buffering middleware?

@julik Can you please provide a minimal self-contained example showing the issue?  Just something simple that uses String#replace in a basic rack app with no dependencies.

**Comment by felixbuenemann** [comment] 2020-12-01 12:15
The buffering @julik talked about is added to prevent tiny writes to the tcp socket as discussed in https://github.com/WeTransfer/zip_tricks/issues/78 and since rack doesn't buffer it has to be implemented on the application side. This is not to say that rack should buffer, since it depends on the use case.

I'm not sure this is something that *can* be solved in rack.

There is no gain from doing dup in rack vs. application side and it causes additional overhead for apps or middleware that does not need it.

---

Taking a step back:

**Shouldn't the rack server itself ensure efficient socket writes?**

Neither the app nor rack should really have to deal with that and the server is the only place where there is enough information to decide how much to buffer based on the socket type and other low level parameters like TLS overhead.

The rack server would have to know when it *must* flush for something like server-sent events.

**Comment by julik** [comment] 2020-12-01 12:23
@jeremyevans sure thing. Imagine you are reading a file and want to reuse a buffer:

```ruby
require 'stringio'
class FileReadingBody
  def each
    random_data = StringIO.new(Random.new.bytes(8 * 1024 * 1024))
    buf = String.new(capacity: 16 * 1024)
    until random_data.eof?
      _ = random_data.read(16*1024, buf)
      yield(buf)
    end
  end
end

app = ->(env) {
  [200, {}, FileReadingBody.new]
}

run app
```

**Comment by julik** [comment] 2020-12-01 12:26
@jeremyevans That's odd. In the project where I encountered the issue I am using rack 2.2.3 and rack-test 1.1.0

I am positive I have observed strings being retained (the actual bug) in usage with rack-test, and did not observe it when running my application in question via Puma 5.0.4. MockResponse in rack-test does contain the buffer iteration with `<<` calls, which should copy the string into the buffer indeed, and it calls out to `super` on the `Rack::Response` from what I could see. But something in `Rack::Response` was retaining.

**Comment by jeremyevans** [comment] 2020-12-01 17:23
So the issue does not appear in `Rack::Response` by default.  It does appear in `Rack::MockResponse` (a subclass) by default, because `Rack::MockResponse` uses `buffered_body!` (from `Rack::Response`).  So if we want to fix `Rack::Response#buffered_body!`:

```diff
diff --git a/lib/rack/response.rb b/lib/rack/response.rb
index 593208fe..9641c3f4 100644
--- a/lib/rack/response.rb
+++ b/lib/rack/response.rb
@@ -266,8 +266,10 @@ module Rack
         if @body.is_a?(Array)
           # The user supplied body was an array:
           @body = @body.compact
-          @body.each do |part|
-            @length += part.to_s.bytesize
+          @body = @body.map do |part|
+            part = part.to_s.dup
+            @length += part.bytesize
+            part
           end
         else
           # Turn the user supplied body into a buffered array:
@@ -275,7 +277,7 @@ module Rack
           @body = Array.new

           body.each do |part|
-            @writer.call(part.to_s)
+            @writer.call(part.to_s.dup)
           end

           body.close if body.respond_to?(:close)
```

Here's the actual example I used for testing:

```ruby
require 'securerandom'
require 'rack'

class FileReadingBody
  def each
    buf = String.new
    3.times do
      buf.replace(SecureRandom.hex(8)) << "\n"
      yield buf
    end
  end
end

app = ->(env) {
  [200, {}, FileReadingBody.new]
}

puts "calling app directly:"
app.call({})[2].each do |str|
  print str
end
puts ""

puts "wrapping app result in Rack::Response"
Rack::Response[*app.call({})].finish[2].each do |str|
  print str
end
puts ""

puts "wrapping app result in Rack::MockResponse"
print Rack::MockResponse[*app.call({})].body
```

As `buffered_body!` is not the default behavior, I don't have an objection to changing this.  I still don't think we should modify SPEC for it, though.

**Comment by julik** [comment] 2020-12-02 12:55
> As buffered_body! is not the default behavior, I don't have an objection to changing this. I still don't think we should modify SPEC for it, though.

Why do you feel that changing the SPEC to mention the possibility of a certain behaviour undesirable?

**Comment by jeremyevans** [comment] 2020-12-02 15:47
> > As buffered_body! is not the default behavior, I don't have an objection to changing this. I still don't think we should modify SPEC for it, though.
> 
> Why do you feel that changing the SPEC to mention the possibility of a certain behaviour is undesirable? Not questioning but trying to understand the perspective

That is questioning, it literally ends in a question mark :) .  To answer your question, I don't think it's something SPEC needs to address.  SPEC should be a specification, not a guideline.  We should only change SPEC to address this if we want to enforce a particular behavior, such as:

1) string bodies yielded to each must not be modified after being yielded (bad for the few applications that want to reuse strings); or
2) servers and middlewares that store the value of strings yielded by each must duplicate the string (bad for all applications that are not reusing strings).

Since either of those two options is problematic, we shouldn't enforce a particular behavior, and therefore this is out of scope of SPEC.

**Comment by julik** [comment] 2020-12-11 11:56
Thanks for the explanation @jeremyevans Although I think there could be a benefit to value semantics in the SPEC (even to the extent of that we mention that these semantics may be undefined) if we can get the MockResponse fixed (and therefore fix rack-test) it would already solve the bulk of the issue for us 🙏

**Comment by ioquatix** [comment] 2021-04-19 08:07
> servers and middlewares that store the value of strings yielded by each must duplicate the string (bad for all applications that are not reusing strings).

With CoW, this option might be less bad than we imagine.

**Comment by nateberkopec** [comment] 2021-04-19 15:28
@ioquatix CoW in CRuby is still pretty unreliable. If, say, one of those strings is also on an OS memory page with another string which gets modified, that "frozen" string will still be copied into the fork's address space.

Aaron's work on compacting helped a little but doesn't (yet) help with CRuby's heap (it only manages the object list, which is a minority of memory use).

**Comment by ioquatix** [comment] 2021-04-19 20:15
@nateberkopec my understanding is strings have fine grained CoW.

**Comment by nateberkopec** [comment] 2021-04-20 13:48
@ioquatix What's that?

I'm just sharing my experience that copy on write behavior is not reliable enough or portable enough to be "counted on" during the design of a feature.

**Comment by ioquatix** [comment] 2021-04-21 02:11
My undersanding is that strings share the same internal buffer if you dup them and don't modify them.

```
def rss
  pid, size = `ps ax -o pid,rss | grep -E "^[[:space:]]*#{$$}"`.strip.split.map(&:to_i)
  return size
end

p rss

buffer = "Hello World" * 100_000

GC.disable

p rss

buffers = 100.times.map do
  buffer.dup

  # Invoke the CoW:
  # buffer += "!"
end

p rss
```

**Comment by ioquatix** [comment] 2022-01-25 06:51
@julik Rack 3.0 will introduce a streaming model which should support your use case. However, we still need to follow through on the server side since I guess at least Falcon won't might sometimes buffer the response string in some cases, so we should ensure that it takes a CoW frozen copy in this case, probably. As such, I'll close this issue.

**Closed by ioquatix** 2022-01-25 06:51 UTC
