### ISSUE TITLE
Read error: #<NoMethodError: undefined method `each' for #<ArgumentError: wrong number of arguments (given 1, expected 2)>>

### ISSUE THREAD

**Issue by daveroberts** [rack/rack#1362] opened 2019-05-17 16:49 UTC
I see similar issues have been reported before for strings being returned.
I'm running puma 3.12.1 and rack 2.0.7
Should puma be capturing the error and returning something different?  As it stands, it very hard to debug errors with this:

```
2019-05-17 12:43:08 -0400: Read error: #<NoMethodError: undefined method `each' for #<ArgumentError: wrong number of arguments (given 1, expected 2)>>
~/.rvm/gems/ruby-2.4.1/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
~/.rvm/gems/ruby-2.4.1/gems/rack-2.0.7/lib/rack/lint.rb:708:in `each'
~/.rvm/gems/ruby-2.4.1/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
~/.rvm/gems/ruby-2.4.1/gems/rack-2.0.7/lib/rack/chunked.rb:23:in `each'
~/.rvm/gems/ruby-2.4.1/gems/puma-3.12.1/lib/puma/server.rb:793:in `handle_request'
~/.rvm/gems/ruby-2.4.1/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
~/.rvm/gems/ruby-2.4.1/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
~/.rvm/gems/ruby-2.4.1/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
I, [2019-05-17T12:47:22.672272 #27487]  INFO -- : User [username] REMOTE_ADDR [127.0.0.1] FORWARDED_FROM [] PATH [/api/something]
```

I would rather see the stack trace associated with the error thrown in my log

**Comment by anatol** [comment] 2020-01-09 17:47
I see somewhat similar error with `rack`+`rack-ouat2` at ruby2.7. It is not clear for me what is the root of the problem. https://gitlab.com/groups/gitlab-org/-/epics/2380#note_269347237

**Comment by ioquatix** [comment] 2020-01-09 21:39
Try using `RUBYOPT=-d` to see all exceptions when they are thrown.

Also, it's odd that the body is wrapping an exception. Should be somewhere in the user middleware?

**Comment by anatol** [comment] 2020-01-09 21:51
@ioquatix The debug journal for this bug is here https://gitlab.com/groups/gitlab-org/-/epics/2380  Honestly I not know the middleware/rack internals and it is not clear for me what is going on there.

**Comment by ioquatix** [comment] 2020-01-09 21:59
@anatol try running with `RUBYOPT=-d` and report back the source of the error.

**Comment by anatol** [comment] 2020-01-10 15:30
I enabled `RUBYOPT=-d` and got a lot of warnings. You might want to look at them here https://pkgbuild.com/~anatolik/gitlab.log.zip

Probably the most relevant is this one:
```
/usr/share/webapps/gitlab/vendor/bundle/ruby/2.7.0/gems/rack-2.0.7/lib/rack/builder.rb:86: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/share/webapps/gitlab/vendor/bundle/ruby/2.7.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:13: warning: The called method `initialize' is defined here
Exception `ArgumentError' at /usr/share/webapps/gitlab/vendor/bundle/ruby/2.7.0/gems/rack-2.0.7/lib/rack/builder.rb:86 - wrong number of arguments (given 3, expected 1..2)
Exception `ArgumentError' at /usr/share/webapps/gitlab/vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:32 - wrong number of arguments (given 3, expected 1..2)
Exception `ArgumentError' at /usr/share/webapps/gitlab/vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:90 - wrong number of arguments (given 3, expected 1..2)
```

**Comment by jeremyevans** [comment] 2020-01-11 22:40
The isssue @anatol brought up was determined to be caused by Grape.  @daveroberts can you run with `RUBYOPT=-d` and provide the output or produce a self-contained reproducible example?  Otherwise, it seems unlikely we can debug it.

FWIW, it seems most likely this problem is an application issue returning an exception as the body, instead of an object that responds to each.

**Comment by ioquatix** [comment] 2020-01-11 22:53
Agreed, this is out of scope for Rack. The only thing I can suggest is putting a middleware at the top of your stack that checks the body and then reports the request details when it's an exception to debug this situation.

**Closed by ioquatix** 2020-01-11 22:53 UTC
