### ISSUE TITLE
How to debug 2.0.7 -> 2.1.2

### ISSUE THREAD

**Issue by resistorsoftware** [rack/rack#1605] opened 2020-02-15 21:45 UTC
So I have an App that was using Rack::Session:Cookie

If I use Rack 2.0.7 my App works in that iframe redirects and cookies are all good. 

If I update to Rack 2.1.2 to use the new same_site: cookie handler, big chunks of my App no longer render. I am curious as to what changed that could be causing this? 

Is there anything in that update path that would be blocking JS or other cookie info?

**Comment by resistorsoftware** [comment] 2020-02-15 22:15
2.0.8 works. Soon as as rebundle to 2.1.0 I lose all my JS processing. Most strange. What the heck happened in that changelog... A simple Sinatra App goes from working to not working just like that.

**Comment by simi** [comment] 2020-02-15 22:30
Can you post some code to reproduce this issue?

**Comment by resistorsoftware** [comment] 2020-02-15 22:49
Good god no... the thing I did... total hack job was... this. I realized that if 2.0.8 works, I will use that. So I forked it, and make a branch for myself off of 2.0.8. I added in the samesite cookie and then re-bundled my App to use that rack. My branch of 2.0.8. So now my App works as usual, and the Chrome browser worked too with all the samesite None settings... 

I am going to be scared moving forward but for now it buys me a little time.

**Comment by jeremyevans** [comment] 2020-02-15 23:37
If you cannot post a failing spec or a minimal self contained reproducible example showing the issue, it is unlikely we will be able to help you. There are many improvements between Rack 2.0.7 and 2.1.2, and quite a few internal changes.  Some software relied on details of the previous implementation, and that has caused some breakage when upgrading.  One example of this is software that was using Rack::Response and providing an incorrect Content-Length header.  It's possible that is the cause of your issue, but it could easily be something else.  It's impossible tell with the information provided.

I'm going to close this now.  If you have evidence that the problems in your app are due to a bug in Rack, please provide them and we can reopen at that point.

**Closed by jeremyevans** 2020-02-15 23:37 UTC
