### ISSUE TITLE
Dynamic cookie key for session stores

### ISSUE THREAD

**Issue by j1mmie** [rack/rack#1155] opened 2017-04-17 18:38 UTC
The abstract session store implementation ([lib/rack/session/abstract/id.rb](https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb)) uses an instance variable, initialized at startup, to determine the name of the cookie it will use to fetch/set a session's id.

I recently ran into a scenario where it would be convenient to have the option to make this cookie name dynamic. For example, a user could visit my website at `www.example.com` and have one session, then they could visit `www.example.com/admin` and have a completely different one. I could also see instances where the session could change dynamically based on cookies, headers, IP address, or any other information the webserver has.

Since these cases are very rare, and may not be best practice, I wanted to get some feedback on this feature request. If there's any desire for such functionality, I'll happily submit a PR.

I'll post one example of how this feature request could be addressed. Please let me know if this is something desirable in the rack mainline.

**Comment by j1mmie** [comment] 2017-04-17 20:46
A simple solution exists in this PR:
https://github.com/rack/rack/pull/1157/files

After this feature, custom session stores would be able to change the cookie key dynamically by overriding the `key` method, for example:

```
class MySessionStore < ActionDispatch::Session::ActiveRecordStore
  def cookie_key(request)
    request.path.starts_with? '/admin' ? '_admin_session_id' : @key
  end
end
```

No tests are written for this change yet. Please let me know if this functionality is desired in rack, or similar functionality with a different implementation, and I'll happily add tests and seek review. Thanks!

**Comment by hiteshsharma** [comment] 2017-05-12 19:48
You can set the key on per request basis accessing `env['rack.session.options']`

for your `/admin` requests add a before_filter to 

```
class MyController
   before_filter :set_cookie_name
    
    def set_cookie_name
       env['rack.session.options'][:key] = "my_cookie_name"
    end
end
```

Do the same for other part of your website you want to have a different cookie name for

**Comment by dachinat** [comment] 2018-10-31 06:38
@j1mmie @hiteshsharma Hi.
I need to isolate 'system.lvh.me' from 'lvh.me', and 'portal.lvh.me'. Means that 'system.lvh.me' should have its own separate session-cookie-store, and 'lvh.me' with 'portal.lvh.me' its own.

I could not make use of `request.env['rack.session.options'][:key] = "my_cookie_name"`

Can you help?

**Comment by j1mmie** [comment] 2018-10-31 15:15
According to hiteshsharma's comment, something like this should work:

```

class MyController
  HOSTS = {
    'system.lvh.me' => 'cookie_key_1',
    'portal.lvh.me' => 'cookie_key_2',
    'lvh.me' => 'cookie_key_3'
  }

   before_filter :set_cookie_name
    
    def set_cookie_name
       request.env['rack.session.options'][:key] = hosts[request.env['HTTP_HOST'].downcase]
    end
end
```

**Comment by dachinat** [comment] 2018-10-31 15:21
@j1mmie Thanks, but `request.env['rack.session.options'][:key` this does not work in Rails 5. I'm trying to monkey-patch / override methods your way. I'm using Rail 5, but no luck yet.

**Comment by dachinat** [comment] 2018-10-31 16:41
@j1mmie this is what I've got now, it kind-of works.. I just added this Rails initializer:

```
class MyCookieStore < ActionDispatch::Session::CookieStore
  # Add this method
  def cookie_key(request)
    request.subdomains[0] == "system" ? :_my_core_system : @key
  end

  # Overrides
  def set_cookie(request, session_id, cookie)
    cookie_jar(request)[cookie_key(request)] = cookie
  end

  def get_cookie(req)
    cookie_jar(req)[cookie_key(req)]
  end
end

Rack::Session::Abstract::Persisted.class_eval do
  # Overrides
  def extract_session_id(request)
    key = cookie_key(request)
    sid = request.cookies[key]
    sid ||= request.params[key] unless @cookie_only
    sid
  end

  def set_cookie(request, res, cookie)
    key = cookie_key(request)
    if request.cookies[key] != cookie[:value] || cookie[:expires]
      res.set_cookie_header =
          Rack::Utils.add_cookie_to_header(res.set_cookie_header, key, cookie)
    end
  end
end

Rails.application.config.session_store :my_cookie_store, key: :_my_core_main, domain: :all, tld_length: 2
```

Thanks for your code btw.

**Comment by j1mmie** [comment] 2018-10-31 19:41
Ah gotcha - glad you're making progress. I think I should reopen this PR because it seems like a useful feature that shouldn't require so much heavy-lifting on the dev's part

**Comment by dachinat** [comment] 2018-10-31 19:49
@j1mmie yes, please do it. 
I also removed `def set_cookie(request, res, cookie)` as it's done by the other class itself.

**Comment by dachinat** [comment] 2018-10-31 19:50
Oh, btw, I think Rails users will need to handle `ActionDispatch::Session::***` too. But as for the Rack your PR is brilliant.

**Comment by jeremyevans** [comment] 2020-01-15 21:14
This is a feature request and not a bug.  It looks like the desired behavior is already possible, just a little bit easier with #1157.  Let's continue any discussion of this on #1157.  Closing this as it is not a bug.

**Closed by jeremyevans** 2020-01-15 21:14 UTC

**Comment by strika** [comment] 2023-11-08 18:32
This is an old issue. It was closed because it was marked as a feature and not a bug and the desired behavior is already possible. However, the author of the issue stated several times that the [proposed solution](https://github.com/rack/rack/issues/1155#issuecomment-301169716) doesn't work.

Another user reported that the proposed solution also doesn't work. Now, I'm noticing the same issue with Rack 2.2.8.

The author of the issue explained why the proposed solution doesn't work in the description of the issue:

> The abstract session store implementation ([lib/rack/session/abstract/id.rb](https://github.com/rack/rack/blob/v2.2.8/lib/rack/session/abstract/id.rb#L253)) uses an instance variable, initialized at startup, to determine the name of the cookie it will use to fetch/set a session's id.

Latter, the instance variable is used to fetch the [session ID](https://github.com/rack/rack/blob/v2.2.8/lib/rack/session/abstract/id.rb#L321).

Changing the session key like this:

```ruby
env['rack.session.options'][:key] = "my_cookie_name"
```

Doesn't have any effect on the instance variable.

I'd like the ask the same question that was asked before. What are we missing?

**Comment by jeremyevans** [comment] 2023-11-08 18:44
Note that the session support was moved into rack-session, so if you have questions regarding this, you can open a discussion in the rack-session repository: https://github.com/rack/rack-session/discussions

**Comment by strika** [comment] 2023-11-16 16:45
Thanks. I created a question about this - https://github.com/rack/rack-session/discussions/25.

However, I still feel that this issue might have been prematurely closed and that this is a bug in Rack. That's because there are some indications (as other people have pointed out) that this is already possible in Rack. But, multiple people reported that it isn't.
