### ISSUE TITLE
complex object parsing issues

### ISSUE THREAD

**Issue by guilherme** [rack/rack#768] opened 2014-12-17 12:02 UTC
The nested query builder aren't  generating a format that is parsed to its original.

``` ruby
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query({simple_test: [{ 1 => [{ 2 =>  [1,2,3,4,5] }] }] }))
# {"simple_test"=>[{"1"=>[{"2"=>[nil, nil, nil, nil, nil]}]}]}
```

``` ruby
Rack::Utils.parse_nested_query({simple_test: [{ 1 => [{ 2 =>  [1,2,3,4,5] }] }] }.to_param) # with rails generating the parameters
# {"simple_test"=>[{"1"=>[{"2"=>["1", "2", "3", "4", "5"]}]}]}
```

I've noted another issue with the parser but i'm not sure what is the problem: with the data format or the builder/parser:

``` ruby
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query({ simple_test: [[1, [[2, [3,2,3,4]]]], [2]] }))
# {"simple_test"=>[nil, nil, nil, nil, nil, nil, nil]}
Rack::Utils.parse_nested_query({ simple_test: [[1, [[2, [3,2,3,4]]]], [2]] }.to_param)
# {"simple_test"=>[nil, nil, nil, nil, nil, nil, nil]}
```

The CGI::parse gives me another output:

``` ruby
CGI::parse({ simple_test: [[1, [[2, [3,2,3,4]]]], [2]] }.to_param)
# {"simple_test[][]"=>["1", "2"], "simple_test[][][][]"=>["2"], "simple_test[][][][][]"=>["3", "2", "3", "4"]}
CGI::parse(Rack::Utils.build_nested_query({ simple_test: [[1, [[2, [3,2,3,4]]]], [2]] }))
# {"simple_test[][]"=>[], "simple_test[][][][]"=>[], "simple_test[][][][][]"=>[]}
```

rack-1.4.5
rails-3.2.11

**Comment by jeremyevans** [comment] 2020-01-17 23:44
The first example in the original post is now handled correctly by rack:

```ruby
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query({simple_test: [{ 1 => [{ 2 =>  [1,2,3,4,5] }] }] }))
# => {"simple_test"=>[{"1"=>[{"2"=>["1", "2", "3", "4", "5"]}]}]}
```

The second case still is not parsed correctly.  Here's a simplified case:

```ruby
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query(a: [[[1]]]))
# => {"a"=>[nil]}
Rack::Utils.build_nested_query(a: [[[1]]])
# => "a[][][]=1"
```

The truth is that Rack cannot parse multiple nested arrays unambiguously:

```ruby
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query(a: [[1], [2]]))
# => => {"a"=>[["1"], ["2"]]}
Rack::Utils.parse_nested_query(Rack::Utils.build_nested_query(a: [[1, 2]]))
# => {"a"=>[["1"], ["2"]]}
```

This is a limitation on the format of submitted parameters.  You should try to avoid having rack parse arrays of anything except scalars.  For more advanced nested data types, try submitting the values as a hash and then converting the hash to an array, or using a different format such as JSON.

Closing this as it is not a bug in rack, just a limitation of the input format.

**Closed by jeremyevans** 2020-01-17 23:44 UTC
