### ISSUE TITLE
Regression with Rack::File.new(nil)

### ISSUE THREAD

**Issue by gverger** [rack/rack#1471] opened 2020-01-11 11:17 UTC
Hello,

I updated rack to 2.1.0 on my Rails 6.0.2.1 app, and it broke with the active storage disk controller.
It seems that it comes from this [line](https://github.com/rails/rails/commit/feab7031b57040afa2b2f5f78f9251dbad6cbdf8#diff-17640e7129bc730594120c1ac91d7928L45) in rails, where `Rack::File.new(nil)` is called.

It has been changed [here](https://github.com/rack/rack/commit/8f85307711ca5e7a4729641fda1552890ffa129a#diff-894804c816a11584eb28499cb8bbe396R25) in version 2.1.0 of Rack.

On the git repository of Rails, it seems this code is not called anymore and that should be fixed in a subsequent version of Rails.

But browsing version 5.2 of Rails showed the same issue [here](https://github.com/rails/rails/blob/13a07268160c1093d4b0ff40e45e487d635fa6b9/activestorage/app/controllers/active_storage/disk_controller.rb#L42), which makes me think the responsibility would come from Rack to fix it.

I think we could just fix it by expanding the root path only when the root path is not nil, but I am not familiar at all with this codebase and it might be more complicated than that.

**Comment by gverger** [comment] 2020-01-11 11:18
FYI there was a Stackoverflow question here starting it: https://stackoverflow.com/questions/59691691/rails-typeerror-no-implicit-conversion-of-nil-into-string-when-loading-image/59693773#59693773

**Comment by tagliala** [comment] 2020-01-11 16:39
Hi, I've stumbled into this

Found a duplicate of this issue: #1464

This has already been fixed on rack master via 1b82d84

**Closed** 2020-01-11 18:17 UTC

**Comment by ioquatix** [comment] 2020-01-11 20:01
I think the rails use case is fragile. We didn't expect root to be nil. However, we've reverted the change and added specs for this use case.
